### ISSUE TITLE
Confirmation token tablosu yapısal hatalar.

### ISSUE THREAD

**Issue by ozziest** [mavidurak/mentor-api#14]
Şu an bir tane `email_confirmation_tokens` tablosu var. Bu tablo sadece e-posta doğrulaması için kullanılıyor. Buradaki yapısal hata şu;

- Eğer bu tablo sadece bu iş için kullanılacaksa, bu tabloya gerek yok. `users` tablosuna doğrudan `confirmation_token` isimli bir alan ekleyebiliriz. Eğer bu alanda bir token varsa, bu bizim için onaylanmamış bir e-posta adresi demektir. Kullanıcı token'ı onayladığında, bu alanı temizleriz. Böylece ikinci bir tabloyla uğraşmayız.

- Eğer bu tablo sadece e-posta doğrulaması için değil, başka doğrulamalar için de oluşturulduysa, bu tablonun adı yanlış. O zaman tablonun adı `confirmation_tokens` gibi bir şey olabilir. Ancak bu sefer de, `token_value` gibi bir alana ek olarak, ilgili doğrulamanın ne için olduğunun bilgisi de tutulmalı. Doğrulama yapılan HTTP isteğinde, token değeriyle birlikte, neyin doğrulaması yapılıyorsa, ilgili veriler ona göre düzenlenmeli.

Şahsi fikrim, birinci yoldan gitmenin daha basit olacağı yönünde.

**Comment by saracalihan** [comment]
' email_confirmation_tokens tablosunun eksikleri kapatıldı #16 ' pr'ı ile çözüldü
