### ISSUE TITLE
ENV değerlerinin key'lerinin güncellenmesi

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#17]
ENV içerisindeki FRONT_END_PATH, BACK_END_PATH ve DATABASE_USERNAME keyleri açık değil. Veriler için ileride MongoDB gibi veritabanları eklenebilir.
FRONT_END ve BACK_END konusuna gelirsek; FRONT_END-DASHBOARD_UI ve BACK_END-API olarak güncellenebilir.

**Comment by saracalihan** [comment]
' email_confirmation_tokens tablosunun eksikleri kapatıldı #16 ' pr'ı ile frontend ve backend path'ları düzeltildi.
