### ISSUE TITLE
Geliştirme ortamında e-posta doğrulamayı daha kolay hale getirmemiz gerekiyor

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#18]
Geliştirme ortamında mail entegrasyonunu yapmamıza gerek kalmadan kullanıcı e-posta adresini hızlıca doğrulayabilmemiz gerekiyor daha hızlı bir test ortamı için.

Geliştirme ortamında (NODE_ENV "development" veya undefined) ise e-posta doğrulamak zorunda kalınmamalı.

**Comment by saracalihan** [comment]
pr: `email_confirmation_tokens tablosunun eksikleri kapatıldı
#16`
