### ISSUE TITLE
users.email_confirmation key'i doğru değil. İsminde boolean olduğunu belirtmemiz daha doğru is_email_confirmed

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#19]
email_confirmation key'i boolean olacağını belirtmiyor. is_email_confirmed daha uygun olabilir.

**Comment by saracalihan** [comment]
' email_confirmation_tokens tablosunun eksikleri kapatıldı #16 ' pr'ı ile çözüldü
