### ISSUE TITLE
Kullanıcı bilgilerinin güncellenmesi

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#20]
Kullanıcının kullanıcı adı değiştirme gibi işlemler tek endpoint içerisinde olabilir. Bu istek "patch" olarak gelmeli. Gelen alanlara göre kullanıcı güncellenmeli.

**Comment by DEONSKY** [comment]
Bu bende

**Comment by DEONSKY** [comment]
Halletim

**Comment by saracalihan** [comment]
@DEONSKY   "user update methods moved to authentications. #27"
