### ISSUE TITLE
Gönderilen e-posta'larda linkler API'a değil Dashboard'a gitmeli.

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#21]
src/utils/sendEmail.js dosyasında e-posta back-end'e değil arayüze yönlenmesi gerekiyor. REST API'ye kullanıcıyı tarayıcı üzerinden yönlendirmek doğru olmaz. Arayüzde bunun için bir sayfa hazırlanması gerekiyor.

**Comment by teathedev** [comment]
@halilseker

**Comment by saracalihan** [comment]
Pr : `issue 21 email confirmation'u dashboard a gonder #30`
