### ISSUE TITLE
DataSets tablosundaki key_title değiştirilmeli.

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#24]
DataSets tablosundaki key_title alanı gelen birim tipini tutacak. Bu yüzden unit_type gibi bir isimlendirme yapılabilir.

**Comment by saracalihan** [comment]
@saracalihan  `key_title` ==> `data_type`

**Comment by saracalihan** [comment]
https://github.com/saracalihan/mentor-api/commit/af994a5785624f6ba54d34d9d55dab8b12c2fdfc
