### ISSUE TITLE
Data'sı bulunan User'ı silme sorunu

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/mentor-api#28]
`datas` tablosunda verisi bulunan bir `user` 'ı silmeye çalıştığımda aldığım hata.

![Screenshot from 2020-10-25 22-37-15](https://user-images.githubusercontent.com/56413673/97150232-df9f2880-177e-11eb-9e1d-14ed902698f3.png)
![Screenshot from 2020-10-25 22-38-16](https://user-images.githubusercontent.com/56413673/97150239-e29a1900-177e-11eb-8d03-bd58c24786a4.png)

**Comment by teathedev** [comment]
@DEONSKY

**Comment by DEONSKY** [comment]
Son açtığım pr ile çözülmüş olmalı. Son eklenen migrationu çalıştırın

**Comment by saracalihan** [comment]
https://github.com/mavidurak/mentor-api/pull/36
