### ISSUE TITLE
Applications tablosunun oluşturulması ve CRUD işlemleri

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#29]
Endpoint'ler url olarak "/applications" ile başlayacak. 
Detail, update ve delete isteklerinde "id" (işlem yapılacak kayıt id'si) url üzerinden alınacak.
src/routes/dataSets/index.js'den örnek alabilirsiniz.

Tablo için: https://github.com/mavidurak/mentor-front-end/blob/master/docs/db.png
Tablo alanarı için: https://github.com/mavidurak/mentor-front-end/blob/master/docs/db.md

**Comment by teathedev** [comment]
@eemredikmen

**Comment by saracalihan** [comment]
https://github.com/mavidurak/mentor-api/pull/37

**Comment by saracalihan** [comment]
@saracalihan
