### ISSUE TITLE
Health check endpoint'i

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-api#43]
`/api/health-check` url'ine istek geldiginde 200 status ile `OK` mesaji donen bir endpoint eklenmesi gerekiyor. Bunun amaci process'in saglikli sekilde ayakta oldugunu bilmek. Production, stating gibi ortamlarda bunu izleyen uygulamalar ile uygulamanin cokusunde otomatik ayaga kaldirma yapilabilir, bildirim gonderilebilir.

**Comment by halilseker** [comment]
@halilseker

**Comment by saracalihan** [comment]
@saracalihan
