### ISSUE TITLE
Application Healtcheck

### ISSUE THREAD

**Issue by DEONSKY** [mavidurak/mentor-api#66]
Kayıtlı applicationdan kullanıcının seçeceği bir süre boyunca ekstra veri gelmemesi durumunda veri tabanında isAlive bilgisi false olarak, veri gelmesi durumunda true olarak değiştirilmesi.
Application tablosuna eklenmesi gereken satırlar: 
isAlive: bool
waitTime: int

**Comment by teathedev** [comment]
Bunun için application healt-check endpoint'i oluşturulup oraya bizim belirlediğimiz sıklıkla istek atılması sağlanabilir. Örneğin application/:applicationId/health-check POST şeklide gelen isteklerle bu uygulamanın status'u eğer alive değilse alive yapabiliriz.
