### ISSUE TITLE
Hata mesajlarını uzunca yazmak yerine Error haline getirilmeli

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/mentor-api#82]
API'da kendimiz hata göderirken şu şekilde gönderiyoruz:
```js
res.send(httpStatus,{
errors: [
  {
    message: 'hata mesajı'
  }
]});
```
Her seferinde bunu uzunca yazmak yerine kendi exception'ımızı yazabiliriz ama burada da her fonksiyonumuzda şu şekilde yazmak gerekiyor:
```js
try {
  // kodlar
  throw new MentorError(httpStatus, "hata mesajı");
} catch(error){
  next(error)
}
// Doğrudan Express'in Error'unu try-catch kullanmadan fırlatabiliyoruz ama hatayı consola basıyor ve kullanıcıya yönlendirsem bile istediğim formatta olmuyor. 
```
Her fonksiyonda try catch yazmaktansa bunu bir middleware vasıtası ile yapmayı orientation-api ile denedim ama okuduğum ve gördüğüm kadarıyla bu çok mümkün değil(veya tercih edilmiyor).

**Comment by teathedev** [comment]
Alttaki gibi yapılmasında bir sakınca yok. Hatta nestjs de bu şekilde handle ediyor. Global error handle middleware'inde classlar üzerinden response düzenlemesi yapabiliriz.
